In [1]:
import os.path as osp
import pandas as pd
import numpy as np
%run env.py
%run src/lib.py
%matplotlib inline

In [2]:
path = osp.join(META_DATA_DIR, CYTOKINES + '.csv')
#path = osp.join(META_DATA_DIR, CELL_TYPES + '.csv')
#path = osp.join(META_DATA_DIR, TRANSCRIPTION_FACTORS + '.csv')
df = pd.read_csv(path)
df.head()

,id,src,sym,lbl,spid,extid,prefid
0,CK16DB62C0EE32FCFC,manual,4-1BB,4-1BB,1,NaN,CK16DB62C0EE32FCFC
1,CKD6A1F8500CF5BB6C,manual,TNFSF9,4-1BB,1,NaN,CK16DB62C0EE32FCFC
2,CK66480A09B13AD79D,cameron,4-1BBL,4-1BBL,1,NaN,CK66480A09B13AD79D
3,CK3C8B23133684A426,cameron,APRIL,APRIL,1,NaN,CK3C8B23133684A426
4,CKA1A67F50E3346A8F,cameron,TALL-2,APRIL,1,NaN,CK3C8B23133684A426

In [3]:
#df[df['sym'].str.len() <= 3]['sym'].unique()

In [11]:
#df[df['sym'].str.upper().str.contains('OX4')]
#df[df['sym'].str.upper().str.contains('ROR')].head(15)
#df[df['sym'].str.lower().str.contains('genesis')].head(15)
#df[df['sym'].str.lower().str.contains('not')].head(15)
#df[df['sym'].str.lower().str.contains('out')].head(15)
df[df['lbl'].str.lower().str.contains('il-17')].head(15)

,id,src,sym,lbl,spid,extid,prefid
841,CK2741EFAE1F31AD65,cameron,IL-17,IL-17,1,NaN,CK2741EFAE1F31AD65
842,CK1A6C6988585C52C3,cameron,CTLA-8,IL-17,1,NaN,CK2741EFAE1F31AD65
843,CK22986C40454409CE,cameron,IL17,IL-17,1,NaN,CK2741EFAE1F31AD65
844,CKE8FA6AFDA083A088,transform,IL-17,IL-17,1,NaN,CK2741EFAE1F31AD65
845,CKBED24729837CC32B,transform,IL17,IL-17,1,NaN,CK2741EFAE1F31AD65
846,CK863AAA27ED3D9692,transform,(IL)17,IL-17,1,NaN,CK2741EFAE1F31AD65
847,CK7454864034311EAE,transform,(IL) 17,IL-17,1,NaN,CK2741EFAE1F31AD65
848,CKECB99947FAE33FCE,transform,(IL)-17,IL-17,1,NaN,CK2741EFAE1F31AD65
849,CK2DAE03460448CD1E,transform,interleukin 17,IL-17,1,NaN,CK2741EFAE1F31AD65
850,CK3487F8736D7E21FF,transform,interleukin-17,IL-17,1,NaN,CK2741EFAE1F31AD65
851,CKE94C3F56154C0ADF,transform,interleukin (IL)-17,IL-17,1,NaN,CK2741EFAE1F31AD65
852,CK08F84BE8FE5B04F8,mygene,IL-17A,IL-17A,1,3605.0,CK08F84BE8FE5B04F8
853,CK45E2B16714C0BC5D,mygene,interleukin 17A,IL-17A,1,3605.0,CK08F84BE8FE5B04F8
854,CKE6475DF2E18B6109,mygene,IL17A,IL-17A,1,3605.0,CK08F84BE8FE5B04F8
855,CK96603F34F4FA96EF,mygene,CTLA-8,IL-17A,1,3605.0,CK08F84BE8FE5B04F8

In [36]:
df[df['sym'].str.upper().str.contains('ROR')]['lbl'].unique()

array(['RORA', 'RORB', 'RORC'], dtype=object)

In [35]:
df[df['lbl'].str.upper() == 'RORC']

,id,src,sym,lbl,spid,extid,prefid
4029,TF765F9A5B1C495BB2,lambert,RORC,RORC,1,ENSG00000143365,TF765F9A5B1C495BB2
4030,TF60A9F7E7158173A5,lambert,RAR related orphan receptor C,RORC,1,ENSG00000143365,TF765F9A5B1C495BB2
4031,TF41F5F4FE0A10A6C8,lambert,IMD42,RORC,1,ENSG00000143365,TF765F9A5B1C495BB2
4032,TFDCC9AABEBEF786D8,lambert,NR1F3,RORC,1,ENSG00000143365,TF765F9A5B1C495BB2
4033,TFFAA0DCD9CD7116F7,lambert,RORG,RORC,1,ENSG00000143365,TF765F9A5B1C495BB2
4034,TF895F457D9E92DCDF,lambert,RZR-GAMMA,RORC,1,ENSG00000143365,TF765F9A5B1C495BB2
4035,TFE8E5BD50A454DE79,lambert,RZRG,RORC,1,ENSG00000143365,TF765F9A5B1C495BB2
4036,TFEA0CF76D98BFD234,lambert,TOR,RORC,1,ENSG00000143365,TF765F9A5B1C495BB2